
package it.greenvulcano.gestpay.wss2s.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSs2sSoap", targetNamespace = "https://ecomms2s.sella.it/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSs2SSoap {


    /**
     * 
     * @param bankTransactionId
     * @param shopTransactionId
     * @param chargeBackFraud
     * @param amount
     * @param uicCode
     * @param refundReason
     * @param orderDetail
     * @param shopLogin
     * @return
     *     returns it.greenvulcano.gestpay.wss2s.model.CallRefundS2SResponse.CallRefundS2SResult
     */
    @WebMethod(action = "https://ecomms2s.sella.it/callRefundS2S")
    @WebResult(name = "callRefundS2SResult", targetNamespace = "https://ecomms2s.sella.it/")
    @RequestWrapper(localName = "callRefundS2S", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallRefundS2S")
    @ResponseWrapper(localName = "callRefundS2SResponse", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallRefundS2SResponse")
    public it.greenvulcano.gestpay.wss2s.model.CallRefundS2SResponse.CallRefundS2SResult callRefundS2S(
        @WebParam(name = "shopLogin", targetNamespace = "https://ecomms2s.sella.it/")
        String shopLogin,
        @WebParam(name = "uicCode", targetNamespace = "https://ecomms2s.sella.it/")
        String uicCode,
        @WebParam(name = "amount", targetNamespace = "https://ecomms2s.sella.it/")
        String amount,
        @WebParam(name = "shopTransactionId", targetNamespace = "https://ecomms2s.sella.it/")
        String shopTransactionId,
        @WebParam(name = "bankTransactionId", targetNamespace = "https://ecomms2s.sella.it/")
        String bankTransactionId,
        @WebParam(name = "OrderDetail", targetNamespace = "https://ecomms2s.sella.it/")
        RefundProductDetail orderDetail,
        @WebParam(name = "RefundReason", targetNamespace = "https://ecomms2s.sella.it/")
        String refundReason,
        @WebParam(name = "chargeBackFraud", targetNamespace = "https://ecomms2s.sella.it/")
        String chargeBackFraud);

    /**
     * 
     * @param bankTransactionId
     * @param shopTransactionId
     * @param shopLogin
     * @return
     *     returns it.greenvulcano.gestpay.wss2s.model.CallReadTrxS2SResponse.CallReadTrxS2SResult
     */
    @WebMethod(action = "https://ecomms2s.sella.it/callReadTrxS2S")
    @WebResult(name = "callReadTrxS2SResult", targetNamespace = "https://ecomms2s.sella.it/")
    @RequestWrapper(localName = "callReadTrxS2S", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallReadTrxS2S")
    @ResponseWrapper(localName = "callReadTrxS2SResponse", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallReadTrxS2SResponse")
    public it.greenvulcano.gestpay.wss2s.model.CallReadTrxS2SResponse.CallReadTrxS2SResult callReadTrxS2S(
        @WebParam(name = "shopLogin", targetNamespace = "https://ecomms2s.sella.it/")
        String shopLogin,
        @WebParam(name = "shopTransactionId", targetNamespace = "https://ecomms2s.sella.it/")
        String shopTransactionId,
        @WebParam(name = "bankTransactionId", targetNamespace = "https://ecomms2s.sella.it/")
        String bankTransactionId);

    /**
     * 
     * @param itemType
     * @param buyerEmail
     * @param idea
     * @param redFraudPrevention
     * @param redBillingInfo
     * @param redShippingInfo
     * @param redCustomerInfo
     * @param expiryYear
     * @param customInfo
     * @param redCustomerData
     * @param transKey
     * @param shopTransactionId
     * @param min
     * @param shippingDetails
     * @param redItems
     * @param clientIP
     * @param recurrent
     * @param shopLogin
     * @param amount
     * @param cvv
     * @param subMerchantId
     * @param uicCode
     * @param applePay
     * @param expiryMonth
     * @param languageId
     * @param buyerName
     * @param orderDetails
     * @param paRes
     * @param requestToken
     * @param redCustomInfo
     * @param tokenValue
     * @param cardNumber
     * @return
     *     returns it.greenvulcano.gestpay.wss2s.model.CallPagamS2SResponse.CallPagamS2SResult
     */
    @WebMethod(action = "https://ecomms2s.sella.it/callPagamS2S")
    @WebResult(name = "callPagamS2SResult", targetNamespace = "https://ecomms2s.sella.it/")
    @RequestWrapper(localName = "callPagamS2S", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallPagamS2S")
    @ResponseWrapper(localName = "callPagamS2SResponse", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallPagamS2SResponse")
    public it.greenvulcano.gestpay.wss2s.model.CallPagamS2SResponse.CallPagamS2SResult callPagamS2S(
        @WebParam(name = "shopLogin", targetNamespace = "https://ecomms2s.sella.it/")
        String shopLogin,
        @WebParam(name = "uicCode", targetNamespace = "https://ecomms2s.sella.it/")
        String uicCode,
        @WebParam(name = "amount", targetNamespace = "https://ecomms2s.sella.it/")
        String amount,
        @WebParam(name = "shopTransactionId", targetNamespace = "https://ecomms2s.sella.it/")
        String shopTransactionId,
        @WebParam(name = "cardNumber", targetNamespace = "https://ecomms2s.sella.it/")
        String cardNumber,
        @WebParam(name = "expiryMonth", targetNamespace = "https://ecomms2s.sella.it/")
        String expiryMonth,
        @WebParam(name = "expiryYear", targetNamespace = "https://ecomms2s.sella.it/")
        String expiryYear,
        @WebParam(name = "buyerName", targetNamespace = "https://ecomms2s.sella.it/")
        String buyerName,
        @WebParam(name = "buyerEmail", targetNamespace = "https://ecomms2s.sella.it/")
        String buyerEmail,
        @WebParam(name = "languageId", targetNamespace = "https://ecomms2s.sella.it/")
        String languageId,
        @WebParam(name = "cvv", targetNamespace = "https://ecomms2s.sella.it/")
        String cvv,
        @WebParam(name = "min", targetNamespace = "https://ecomms2s.sella.it/")
        String min,
        @WebParam(name = "transKey", targetNamespace = "https://ecomms2s.sella.it/")
        String transKey,
        @WebParam(name = "PARes", targetNamespace = "https://ecomms2s.sella.it/")
        String paRes,
        @WebParam(name = "customInfo", targetNamespace = "https://ecomms2s.sella.it/")
        String customInfo,
        @WebParam(name = "IDEA", targetNamespace = "https://ecomms2s.sella.it/")
        String idea,
        @WebParam(name = "requestToken", targetNamespace = "https://ecomms2s.sella.it/")
        String requestToken,
        @WebParam(name = "tokenValue", targetNamespace = "https://ecomms2s.sella.it/")
        String tokenValue,
        @WebParam(name = "clientIP", targetNamespace = "https://ecomms2s.sella.it/")
        String clientIP,
        @WebParam(name = "itemType", targetNamespace = "https://ecomms2s.sella.it/")
        String itemType,
        @WebParam(name = "recurrent", targetNamespace = "https://ecomms2s.sella.it/")
        String recurrent,
        @WebParam(name = "subMerchantId", targetNamespace = "https://ecomms2s.sella.it/")
        String subMerchantId,
        @WebParam(name = "shippingDetails", targetNamespace = "https://ecomms2s.sella.it/")
        ShippingDetails shippingDetails,
        @WebParam(name = "redFraudPrevention", targetNamespace = "https://ecomms2s.sella.it/")
        String redFraudPrevention,
        @WebParam(name = "Red_CustomerInfo", targetNamespace = "https://ecomms2s.sella.it/")
        RedCustomerInfo redCustomerInfo,
        @WebParam(name = "Red_ShippingInfo", targetNamespace = "https://ecomms2s.sella.it/")
        RedShippingInfo redShippingInfo,
        @WebParam(name = "Red_BillingInfo", targetNamespace = "https://ecomms2s.sella.it/")
        RedBillingInfo redBillingInfo,
        @WebParam(name = "Red_CustomerData", targetNamespace = "https://ecomms2s.sella.it/")
        RedCustomerData redCustomerData,
        @WebParam(name = "Red_CustomInfo", targetNamespace = "https://ecomms2s.sella.it/")
        RedCustomInfo redCustomInfo,
        @WebParam(name = "Red_Items", targetNamespace = "https://ecomms2s.sella.it/")
        RedItems redItems,
        @WebParam(name = "applePay", targetNamespace = "https://ecomms2s.sella.it/")
        ApplePayRequest applePay,
        @WebParam(name = "OrderDetails", targetNamespace = "https://ecomms2s.sella.it/")
        EcommGestpayPaymentDetails orderDetails);

    /**
     * 
     * @param bankTransactionId
     * @param shopTransactionId
     * @param cancelReason
     * @param shopLogin
     * @return
     *     returns it.greenvulcano.gestpay.wss2s.model.CallDeleteS2SResponse.CallDeleteS2SResult
     */
    @WebMethod(action = "https://ecomms2s.sella.it/callDeleteS2S")
    @WebResult(name = "callDeleteS2SResult", targetNamespace = "https://ecomms2s.sella.it/")
    @RequestWrapper(localName = "callDeleteS2S", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallDeleteS2S")
    @ResponseWrapper(localName = "callDeleteS2SResponse", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallDeleteS2SResponse")
    public it.greenvulcano.gestpay.wss2s.model.CallDeleteS2SResponse.CallDeleteS2SResult callDeleteS2S(
        @WebParam(name = "shopLogin", targetNamespace = "https://ecomms2s.sella.it/")
        String shopLogin,
        @WebParam(name = "shopTransactionId", targetNamespace = "https://ecomms2s.sella.it/")
        String shopTransactionId,
        @WebParam(name = "bankTransactionId", targetNamespace = "https://ecomms2s.sella.it/")
        String bankTransactionId,
        @WebParam(name = "CancelReason", targetNamespace = "https://ecomms2s.sella.it/")
        String cancelReason);

    /**
     * 
     * @param amount
     * @param bankTransID
     * @param uicCode
     * @param fullFillment
     * @param shopTransID
     * @param shopLogin
     * @return
     *     returns it.greenvulcano.gestpay.wss2s.model.CallSettleS2SResponse.CallSettleS2SResult
     */
    @WebMethod(action = "https://ecomms2s.sella.it/callSettleS2S")
    @WebResult(name = "callSettleS2SResult", targetNamespace = "https://ecomms2s.sella.it/")
    @RequestWrapper(localName = "callSettleS2S", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallSettleS2S")
    @ResponseWrapper(localName = "callSettleS2SResponse", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallSettleS2SResponse")
    public it.greenvulcano.gestpay.wss2s.model.CallSettleS2SResponse.CallSettleS2SResult callSettleS2S(
        @WebParam(name = "shopLogin", targetNamespace = "https://ecomms2s.sella.it/")
        String shopLogin,
        @WebParam(name = "uicCode", targetNamespace = "https://ecomms2s.sella.it/")
        String uicCode,
        @WebParam(name = "amount", targetNamespace = "https://ecomms2s.sella.it/")
        String amount,
        @WebParam(name = "shopTransID", targetNamespace = "https://ecomms2s.sella.it/")
        String shopTransID,
        @WebParam(name = "bankTransID", targetNamespace = "https://ecomms2s.sella.it/")
        String bankTransID,
        @WebParam(name = "FullFillment", targetNamespace = "https://ecomms2s.sella.it/")
        FullFillmentDetails fullFillment);

    /**
     * 
     * @param shopTransactionId
     * @param expMonth
     * @param cvv2
     * @param expYear
     * @param shopLogin
     * @param cardNumber
     * @return
     *     returns it.greenvulcano.gestpay.wss2s.model.CallVerifycardS2SResponse.CallVerifycardS2SResult
     */
    @WebMethod(action = "https://ecomms2s.sella.it/callVerifycardS2S")
    @WebResult(name = "callVerifycardS2SResult", targetNamespace = "https://ecomms2s.sella.it/")
    @RequestWrapper(localName = "callVerifycardS2S", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallVerifycardS2S")
    @ResponseWrapper(localName = "callVerifycardS2SResponse", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallVerifycardS2SResponse")
    public it.greenvulcano.gestpay.wss2s.model.CallVerifycardS2SResponse.CallVerifycardS2SResult callVerifycardS2S(
        @WebParam(name = "shopLogin", targetNamespace = "https://ecomms2s.sella.it/")
        String shopLogin,
        @WebParam(name = "shopTransactionId", targetNamespace = "https://ecomms2s.sella.it/")
        String shopTransactionId,
        @WebParam(name = "cardNumber", targetNamespace = "https://ecomms2s.sella.it/")
        String cardNumber,
        @WebParam(name = "expMonth", targetNamespace = "https://ecomms2s.sella.it/")
        String expMonth,
        @WebParam(name = "expYear", targetNamespace = "https://ecomms2s.sella.it/")
        String expYear,
        @WebParam(name = "CVV2", targetNamespace = "https://ecomms2s.sella.it/")
        String cvv2);

    /**
     * 
     * @param shopTransactionId
     * @param expMonth
     * @param cvv2
     * @param expYear
     * @param withAuth
     * @param tokenValue
     * @param shopLogin
     * @param cardNumber
     * @return
     *     returns it.greenvulcano.gestpay.wss2s.model.CallCheckCartaS2SResponse.CallCheckCartaS2SResult
     */
    @WebMethod(action = "https://ecomms2s.sella.it/callCheckCartaS2S")
    @WebResult(name = "callCheckCartaS2SResult", targetNamespace = "https://ecomms2s.sella.it/")
    @RequestWrapper(localName = "callCheckCartaS2S", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallCheckCartaS2S")
    @ResponseWrapper(localName = "callCheckCartaS2SResponse", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallCheckCartaS2SResponse")
    public it.greenvulcano.gestpay.wss2s.model.CallCheckCartaS2SResponse.CallCheckCartaS2SResult callCheckCartaS2S(
        @WebParam(name = "shopLogin", targetNamespace = "https://ecomms2s.sella.it/")
        String shopLogin,
        @WebParam(name = "shopTransactionId", targetNamespace = "https://ecomms2s.sella.it/")
        String shopTransactionId,
        @WebParam(name = "cardNumber", targetNamespace = "https://ecomms2s.sella.it/")
        String cardNumber,
        @WebParam(name = "expMonth", targetNamespace = "https://ecomms2s.sella.it/")
        String expMonth,
        @WebParam(name = "expYear", targetNamespace = "https://ecomms2s.sella.it/")
        String expYear,
        @WebParam(name = "CVV2", targetNamespace = "https://ecomms2s.sella.it/")
        String cvv2,
        @WebParam(name = "withAuth", targetNamespace = "https://ecomms2s.sella.it/")
        String withAuth,
        @WebParam(name = "tokenValue", targetNamespace = "https://ecomms2s.sella.it/")
        String tokenValue);

    /**
     * 
     * @return
     *     returns it.greenvulcano.gestpay.wss2s.model.CallRenounceResponse.CallRenounceResult
     */
    @WebMethod(action = "https://ecomms2s.sella.it/callRenounce")
    @WebResult(name = "callRenounceResult", targetNamespace = "https://ecomms2s.sella.it/")
    @RequestWrapper(localName = "callRenounce", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallRenounce")
    @ResponseWrapper(localName = "callRenounceResponse", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallRenounceResponse")
    public it.greenvulcano.gestpay.wss2s.model.CallRenounceResponse.CallRenounceResult callRenounce();

    /**
     * 
     * @param cvv
     * @param expiryMonth
     * @param requestToken
     * @param expiryYear
     * @param withAuth
     * @param shopLogin
     * @param cardNumber
     * @return
     *     returns it.greenvulcano.gestpay.wss2s.model.CallRequestTokenS2SResponse.CallRequestTokenS2SResult
     */
    @WebMethod(operationName = "CallRequestTokenS2S", action = "https://ecomms2s.sella.it/CallRequestTokenS2S")
    @WebResult(name = "CallRequestTokenS2SResult", targetNamespace = "https://ecomms2s.sella.it/")
    @RequestWrapper(localName = "CallRequestTokenS2S", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallRequestTokenS2S")
    @ResponseWrapper(localName = "CallRequestTokenS2SResponse", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallRequestTokenS2SResponse")
    public it.greenvulcano.gestpay.wss2s.model.CallRequestTokenS2SResponse.CallRequestTokenS2SResult callRequestTokenS2S(
        @WebParam(name = "shopLogin", targetNamespace = "https://ecomms2s.sella.it/")
        String shopLogin,
        @WebParam(name = "requestToken", targetNamespace = "https://ecomms2s.sella.it/")
        String requestToken,
        @WebParam(name = "cardNumber", targetNamespace = "https://ecomms2s.sella.it/")
        String cardNumber,
        @WebParam(name = "expiryMonth", targetNamespace = "https://ecomms2s.sella.it/")
        String expiryMonth,
        @WebParam(name = "expiryYear", targetNamespace = "https://ecomms2s.sella.it/")
        String expiryYear,
        @WebParam(name = "cvv", targetNamespace = "https://ecomms2s.sella.it/")
        String cvv,
        @WebParam(name = "withAuth", targetNamespace = "https://ecomms2s.sella.it/")
        String withAuth);

    /**
     * 
     * @param tokenValue
     * @param shopLogin
     * @return
     *     returns it.greenvulcano.gestpay.wss2s.model.CallDeleteTokenS2SResponse.CallDeleteTokenS2SResult
     */
    @WebMethod(action = "https://ecomms2s.sella.it/callDeleteTokenS2S")
    @WebResult(name = "callDeleteTokenS2SResult", targetNamespace = "https://ecomms2s.sella.it/")
    @RequestWrapper(localName = "callDeleteTokenS2S", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallDeleteTokenS2S")
    @ResponseWrapper(localName = "callDeleteTokenS2SResponse", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallDeleteTokenS2SResponse")
    public it.greenvulcano.gestpay.wss2s.model.CallDeleteTokenS2SResponse.CallDeleteTokenS2SResult callDeleteTokenS2S(
        @WebParam(name = "tokenValue", targetNamespace = "https://ecomms2s.sella.it/")
        String tokenValue,
        @WebParam(name = "shopLogin", targetNamespace = "https://ecomms2s.sella.it/")
        String shopLogin);

    /**
     * 
     * @param expiryMonth
     * @param expiryYear
     * @param shopLogin
     * @param token
     * @param withAut
     * @return
     *     returns it.greenvulcano.gestpay.wss2s.model.CallUpdateTokenS2SResponse.CallUpdateTokenS2SResult
     */
    @WebMethod(operationName = "CallUpdateTokenS2S", action = "https://ecomms2s.sella.it/CallUpdateTokenS2S")
    @WebResult(name = "CallUpdateTokenS2SResult", targetNamespace = "https://ecomms2s.sella.it/")
    @RequestWrapper(localName = "CallUpdateTokenS2S", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallUpdateTokenS2S")
    @ResponseWrapper(localName = "CallUpdateTokenS2SResponse", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallUpdateTokenS2SResponse")
    public it.greenvulcano.gestpay.wss2s.model.CallUpdateTokenS2SResponse.CallUpdateTokenS2SResult callUpdateTokenS2S(
        @WebParam(name = "shopLogin", targetNamespace = "https://ecomms2s.sella.it/")
        String shopLogin,
        @WebParam(name = "token", targetNamespace = "https://ecomms2s.sella.it/")
        String token,
        @WebParam(name = "expiryMonth", targetNamespace = "https://ecomms2s.sella.it/")
        String expiryMonth,
        @WebParam(name = "expiryYear", targetNamespace = "https://ecomms2s.sella.it/")
        String expiryYear,
        @WebParam(name = "withAut", targetNamespace = "https://ecomms2s.sella.it/")
        String withAut);

    /**
     * 
     * @param shopLogin
     * @return
     *     returns it.greenvulcano.gestpay.wss2s.model.CallIdealListS2SResponse.CallIdealListS2SResult
     */
    @WebMethod(operationName = "CallIdealListS2S", action = "https://ecomms2s.sella.it/CallIdealListS2S")
    @WebResult(name = "CallIdealListS2SResult", targetNamespace = "https://ecomms2s.sella.it/")
    @RequestWrapper(localName = "CallIdealListS2S", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallIdealListS2S")
    @ResponseWrapper(localName = "CallIdealListS2SResponse", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallIdealListS2SResponse")
    public it.greenvulcano.gestpay.wss2s.model.CallIdealListS2SResponse.CallIdealListS2SResult callIdealListS2S(
        @WebParam(name = "shopLogin", targetNamespace = "https://ecomms2s.sella.it/")
        String shopLogin);

    /**
     * 
     * @param languageId
     * @param shopLogin
     * @return
     *     returns it.greenvulcano.gestpay.wss2s.model.CallMyBankListS2SResponse.CallMyBankListS2SResult
     */
    @WebMethod(operationName = "CallMyBankListS2S", action = "https://ecomms2s.sella.it/CallMyBankListS2S")
    @WebResult(name = "CallMyBankListS2SResult", targetNamespace = "https://ecomms2s.sella.it/")
    @RequestWrapper(localName = "CallMyBankListS2S", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallMyBankListS2S")
    @ResponseWrapper(localName = "CallMyBankListS2SResponse", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallMyBankListS2SResponse")
    public it.greenvulcano.gestpay.wss2s.model.CallMyBankListS2SResponse.CallMyBankListS2SResult callMyBankListS2S(
        @WebParam(name = "shopLogin", targetNamespace = "https://ecomms2s.sella.it/")
        String shopLogin,
        @WebParam(name = "languageId", targetNamespace = "https://ecomms2s.sella.it/")
        String languageId);

    /**
     * 
     * @param bankTransactionId
     * @param shopTransactionId
     * @param paramName
     * @param shopLogin
     * @param paramValue
     * @return
     *     returns it.greenvulcano.gestpay.wss2s.model.CallUpdateCustomParamS2SResponse.CallUpdateCustomParamS2SResult
     */
    @WebMethod(operationName = "CallUpdateCustomParamS2S", action = "https://ecomms2s.sella.it/CallUpdateCustomParamS2S")
    @WebResult(name = "CallUpdateCustomParamS2SResult", targetNamespace = "https://ecomms2s.sella.it/")
    @RequestWrapper(localName = "CallUpdateCustomParamS2S", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallUpdateCustomParamS2S")
    @ResponseWrapper(localName = "CallUpdateCustomParamS2SResponse", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallUpdateCustomParamS2SResponse")
    public it.greenvulcano.gestpay.wss2s.model.CallUpdateCustomParamS2SResponse.CallUpdateCustomParamS2SResult callUpdateCustomParamS2S(
        @WebParam(name = "shopLogin", targetNamespace = "https://ecomms2s.sella.it/")
        String shopLogin,
        @WebParam(name = "shopTransactionId", targetNamespace = "https://ecomms2s.sella.it/")
        String shopTransactionId,
        @WebParam(name = "bankTransactionId", targetNamespace = "https://ecomms2s.sella.it/")
        String bankTransactionId,
        @WebParam(name = "paramName", targetNamespace = "https://ecomms2s.sella.it/")
        String paramName,
        @WebParam(name = "paramValue", targetNamespace = "https://ecomms2s.sella.it/")
        String paramValue);

    /**
     * 
     * @param bankTransactionId
     * @param shopTransactionId
     * @param orderDetails
     * @param shopLogin
     * @return
     *     returns it.greenvulcano.gestpay.wss2s.model.CallUpdateOrderS2SResponse.CallUpdateOrderS2SResult
     */
    @WebMethod(operationName = "CallUpdateOrderS2S", action = "https://ecomms2s.sella.it/CallUpdateOrderS2S")
    @WebResult(name = "CallUpdateOrderS2SResult", targetNamespace = "https://ecomms2s.sella.it/")
    @RequestWrapper(localName = "CallUpdateOrderS2S", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallUpdateOrderS2S")
    @ResponseWrapper(localName = "CallUpdateOrderS2SResponse", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallUpdateOrderS2SResponse")
    public it.greenvulcano.gestpay.wss2s.model.CallUpdateOrderS2SResponse.CallUpdateOrderS2SResult callUpdateOrderS2S(
        @WebParam(name = "shopLogin", targetNamespace = "https://ecomms2s.sella.it/")
        String shopLogin,
        @WebParam(name = "shopTransactionId", targetNamespace = "https://ecomms2s.sella.it/")
        String shopTransactionId,
        @WebParam(name = "bankTransactionId", targetNamespace = "https://ecomms2s.sella.it/")
        String bankTransactionId,
        @WebParam(name = "OrderDetails", targetNamespace = "https://ecomms2s.sella.it/")
        EcommGestpayPaymentDetails orderDetails);

    /**
     * 
     * @param numericIsoCode
     * @param uicCode
     * @param isoCode
     * @param shopLogin
     * @return
     *     returns it.greenvulcano.gestpay.wss2s.model.CallExchangeRateS2SResponse.CallExchangeRateS2SResult
     */
    @WebMethod(action = "https://ecomms2s.sella.it/callExchangeRateS2S")
    @WebResult(name = "callExchangeRateS2SResult", targetNamespace = "https://ecomms2s.sella.it/")
    @RequestWrapper(localName = "callExchangeRateS2S", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallExchangeRateS2S")
    @ResponseWrapper(localName = "callExchangeRateS2SResponse", targetNamespace = "https://ecomms2s.sella.it/", className = "it.greenvulcano.gestpay.wss2s.model.CallExchangeRateS2SResponse")
    public it.greenvulcano.gestpay.wss2s.model.CallExchangeRateS2SResponse.CallExchangeRateS2SResult callExchangeRateS2S(
        @WebParam(name = "shopLogin", targetNamespace = "https://ecomms2s.sella.it/")
        String shopLogin,
        @WebParam(name = "uicCode", targetNamespace = "https://ecomms2s.sella.it/")
        String uicCode,
        @WebParam(name = "isoCode", targetNamespace = "https://ecomms2s.sella.it/")
        String isoCode,
        @WebParam(name = "numericIsoCode", targetNamespace = "https://ecomms2s.sella.it/")
        String numericIsoCode);

}
